### ISSUE TITLE
block argument in Cepo not working

### ISSUE THREAD

**Issue by retogerber** [PYangLab/Cepo#2]
Hi

It seems that specifying the `block` argument in `Cepo` doesn't work, the same result is returned multiple times. Looking at the code it seems that the wrong input is given for `singleBatchCepo` when having a block. On lines 86 and 87 instead of
```     
singleBatch <- singleBatchCepo(exprsMat = exprsMat, cellTypes = cellTypes, ...)
```
I think it should be
```
singleBatch <- singleBatchCepo(exprsMat = exprsMat_batch, cellTypes = cellTypes_batch, ...)
```
Thanks!

**Comment by HaniJieunKim** [comment]
Hi @retogerber! 

Thanks a lot for raising this. I have fixed the bug. Please could you re-install Cepo and try again? 

Best regards,

Hani

**Comment by retogerber** [comment]
Hi @HaniJieunKim 

Thanks a lot for the fast reply and fix. Seems to work now.
